// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPHxLN0yhtYcdJAeknAoW-zNBysRF8hJ8',
    appId: '1:879396917356:web:27185d303c8d6289f78849',
    messagingSenderId: '879396917356',
    projectId: 'ai-discovery-app-b3a9d',
    authDomain: 'ai-discovery-app-b3a9d.firebaseapp.com',
    storageBucket: 'ai-discovery-app-b3a9d.firebasestorage.app',
    measurementId: 'G-2NRRR79Y1W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUwM8pUjHdZa-QYcf2gIpPXtTq49_mDZA',
    appId: '1:879396917356:android:5ba28ab6e3bed239f78849',
    messagingSenderId: '879396917356',
    projectId: 'ai-discovery-app-b3a9d',
    storageBucket: 'ai-discovery-app-b3a9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaerLu7Oe406x85dKCHRKMyoOb2lKJILU',
    appId: '1:879396917356:ios:c5f69ef3a8a7a0c6f78849',
    messagingSenderId: '879396917356',
    projectId: 'ai-discovery-app-b3a9d',
    storageBucket: 'ai-discovery-app-b3a9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaerLu7Oe406x85dKCHRKMyoOb2lKJILU',
    appId: '1:879396917356:ios:c5f69ef3a8a7a0c6f78849',
    messagingSenderId: '879396917356',
    projectId: 'ai-discovery-app-b3a9d',
    storageBucket: 'ai-discovery-app-b3a9d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPHxLN0yhtYcdJAeknAoW-zNBysRF8hJ8',
    appId: '1:879396917356:web:622c5408dabd64e7f78849',
    messagingSenderId: '879396917356',
    projectId: 'ai-discovery-app-b3a9d',
    authDomain: 'ai-discovery-app-b3a9d.firebaseapp.com',
    storageBucket: 'ai-discovery-app-b3a9d.firebasestorage.app',
    measurementId: 'G-RJMWLKR9VD',
  );
}
